---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
  - include_role:
      name: nginxinc.nginx_controller.nginx_controller_generate_token

  - name: Get controller api key for agent registration
    uri:
      url: "https://{{ nginx_controller_fqdn }}/api/v1/platform/global"
      method: "GET"
      return_content: yes
      status_code: 200
      validate_certs: false
      headers:
        Cookie: "{{ nginx_controller_auth_token }}"
    register: ctrl_globals

  - name: Copy api_key to a variable
    set_fact:
      api_key: "{{ctrl_globals.json.currentStatus.agentSettings.apiKey}}"

- hosts: tag_new_gateway
  remote_user: "{{ remoteUser }}"
  become: true
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: install minimal support for python2 for Ubuntu
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python-minimal
      # - libxerces-c3.2
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: install minimal support for python2 for RHEL
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python2
      # - xerces-c
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: install the agent
    include_role:
      name: nginxinc.nginx_controller.nginx_controller_agent
    vars:
      nginx_controller_hostname: "{{ ansible_facts['fqdn'] }}"
      nginx_controller_api_key: "{{ hostvars['localhost']['api_key'] }}"
      nginx_controller_instance_name: "{{ ansible_facts['fqdn'] }}"
      # location: 
