env:
  nginx_controller_auth_token: '{{nginxControllerToken}}'
  nginx_controller_fqdn: '{{nginxControllerDNS}}'
  nginx_controller_user_email: '{{controllerUserEmail}}'
  nginx_controller_user_password: '{{controllerUserPassword}}'
extra_vars:
  nginx_controller_auth_token: '{{nginxControllerToken}}'
  nginx_controller_fqdn: '{{nginxControllerDNS}}'
  nginx_controller_user_email: '{{controllerUserEmail}}'
  nginx_controller_user_password: '{{controllerUserPassword}}'
