fields:
  - id: nginxControllerUserEmail
    type: string
    label: NGINX Controller user email address
  - id: nginxControllerUserPassword
    type: string
    label: NGINX Controller user password
    secret: true
  - id: nginxControllerDNS
    type: string
    label: NGINX Controller DNS or IP address
required:
  - nginxControllerUserEmail
  - nginxControllerUserPassword
  - nginxControllerDNS
